### ISSUE TITLE
Clickhouse Operator Node Selector

### ISSUE THREAD

**Issue by jholm117** [SigNoz/charts#117]
https://github.com/SigNoz/charts/blob/9049196823239421f02f3752af0734f498712694/charts/clickhouse/values.yaml#L364

Hello, just want to point out that this value does not seem to have the intended effect of adding a node selector to the clickhouse operator deployment. I checked the deployment [template](https://github.com/SigNoz/charts/blob/main/charts/clickhouse/templates/clickhouse-operator/deployment.yaml) and confirmed it was absent.

**Comment by prashant-shahi** [comment]
@jholm117 Thanks for raising this issue.

The link you have shared is for clickhouse-operator but not clickhouse instance itself.

`nodeSelector` is applied for ClickHouse Instance instead: https://github.com/SigNoz/charts/blob/main/charts/clickhouse/templates/clickhouse-instance.yaml#L136.

Could you please verify it the `nodeSelector` worked on clickhouse `chi` pods?

**Comment by jholm117** [comment]
Oh okay, I understand though it still seems there is no way to put a node selector on the operator deployment (my ultimate goal).

**Comment by prashant-shahi** [comment]
@jholm117 yes, you are right. Looks like that was missed for the operator deployment. Thanks for pointing out.

Feel free to raise a PR to include it, if possible.
