### ISSUE TITLE
Error: parse array of log path 

### ISSUE THREAD

**Issue by stok1y** [SigNoz/charts#120]
Hi there.
You can improve this part: https://github.com/SigNoz/charts/blob/1a352acb593af3fd366ce200ec4fd742efc8e1f2/charts/signoz/values.yaml#L1699

**Because, when i added new line i got next situation**

Values.yaml:
```
      include:
        - /var/log/containers/*.log
        - /var/log/pods/*/*/*.log
```
        
Configmap:
```
    include:
    - /var/log/containers/*.log /var/log/pods/*/*/*.log
```

Error:
```
warn fileconsumer/file.go:61 no files match the configured include patterns {"kind": "receiver", "name": "filelog/k8s", "pipeline": "logs", "component": "fileconsumer", "include": ["/var/log/containers/*.log /var/log/pods/*/*/*.log"], "exclude": []}
```

_Originally posted by @stok1y in https://github.com/SigNoz/signoz/discussions/713#discussioncomment-4508787_

**Comment by prashant-shahi** [comment]
@stok1y Thanks for raising this issue.

This issue is fixed in https://github.com/SigNoz/charts/pull/124 which is included in latest release.
