### ISSUE TITLE
redundant and invalid low values returned from some kubelet metrics

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/charts#122]
There can be seen redundant metrics with `k8s_*` and `container_*` metrics.
While k8s resource requests/limits, seem to have invalid data like instead of `100`, the value was `0.1`.
Possibly caused by difference in unit.

**Comment by srikanthccv** [comment]
>There can be seen redundant metrics with k8s_* and container_* metrics.

If you could share some samples that would help make it more clear. Which one did find redundant?

> While k8s resource requests/limits, seem to have invalid data like instead of 100, the value was 0.1.

Please elaborate on this also with an example of what is happening vs what's expected

**Comment by prashant-shahi** [comment]
> Please elaborate on this also with an example of what is happening vs what's expected

`k8s_container_cpu_request` for example returns two different values: `0.1` and `100`

![Screenshot from 2022-12-29 09-21-17](https://user-images.githubusercontent.com/11138844/209901199-c30ef4bc-af3e-4765-9575-63df78f2734d.png)

**Comment by prashant-shahi** [comment]
This issue has been resolved now with recent changes with processor and envs.
