### ISSUE TITLE
SigNoz chart values.yaml global.image.registry not respected

### ISSUE THREAD

**Issue by patrijua** [SigNoz/charts#129]
In SigNoz Helm chart values.yaml, there is a global setting of image registry global.image.registry but it is not working. Even though setting the value for global.image.registry when installing SigNoz chart, rendered  chart contains still contains references to docker.io registy, for example:

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: signoz-query-service
  labels:
    helm.sh/chart: signoz-0.7.1
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: query-service
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: signoz-query-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: signoz
      app.kubernetes.io/instance: signoz
      app.kubernetes.io/component: query-service
  template:
    metadata:
      annotations:
        checksum/config: e9cdc72b583fd6c977f6942e4dc1f4c5749f6601cf147585de13ba210cf14e99
      labels:
        app.kubernetes.io/name: signoz
        app.kubernetes.io/instance: signoz
        app.kubernetes.io/component: query-service
    spec:
      serviceAccountName: signoz-query-service
      securityContext:
        {}
      initContainers:
        - name: signoz-query-service-init
          image: docker.io/busybox:1.35

**Comment by patrijua** [comment]
Seems like most of init containers are not using the global setting, but also also others like signoz-zookeeper StatefulSet is not respecting the global setting. When rendering the chart for example by command 

`helm template signoz signoz/signoz --set global.image.registry=abcd.com/docker`

Rendered chart consists six different references to `image: docker.io`

**Comment by prashant-shahi** [comment]
@patrijua Thanks for raising the issue.

It is resolved by the PR linked above and the fix will be part of the next chart release.
