### ISSUE TITLE
Support `existingClaim` for `queryService.persistence` and `alertmanager.persistence`

### ISSUE THREAD

**Issue by sebastiaopamplona** [SigNoz/charts#131]
Hi, first of all I would just like to say that setting up SigNoz using helm was seamless :)

However my cluster does not have `Dynamic Volume Provisioning` enabled.
Hence I would like to ask if it's possible to support `existingClaim` in `queryService. persistence` and `alertmanager.persistence`, similar to how it is possible for `clickhouse.persistence`.

The use case for this is that if for some reason I want to redeploy SigNoz on my cluster, I want to control which persistent volumes each service will get.
Yesterday I was testing outage scenarios and came across the following situation:
1. Create 4 persistent volumes (pv1, pv2, pv3, pv4)
2. Deploy SigNoz
3. The query service persistent volume claim gets pv2
4. Register user
5. Remove SigNoz from the cluster
6. Deploy SigNoz again
7. The query service persistent volume claim gets pv3
8. The user registered in 4. is not found

**Comment by sebastiaopamplona** [comment]
@prashant-shahi any update on this?

**Comment by prashant-shahi** [comment]
@sebastiaopamplona We are working on it at the moment. It should be done in few days. And included in the upcoming chart release.
