### ISSUE TITLE
Can otel-collector-metrics be disabled

### ISSUE THREAD

**Issue by vasicvuk** [SigNoz/charts#147]
Can otel-collector-metrics be disabled?

**Comment by srikanthccv** [comment]
Technically, it could be disabled (with some config changes), but we recommend not doing that. It scrapes the APM metrics and internal metrics of the main collector(s).

If you were to disable that the internal metrics need to be monitored by some system, that system could be the collector itself, but the issue with this is when the collector is having problems with its pipelines, this collector monitoring data may get lost which is essential when things go wrong. We also suggest using this as a Prometheus scraper for people with some systems instrumented using its client libraries and exporters. The benefits of having this outweigh the drawbacks (what are your concerns other than the extra pod?).

**Comment by vasicvuk** [comment]
Just an extra pod, and resource consumption.

**Comment by prashant-shahi** [comment]
@vasicvuk OtelCollector Metrics is responsible for scraping signoz spanmetrics, internal collectors metrics and other external metrics enabled via prometheus config or pod annotations.

Default page of SigNoz UI i.e. services page will be affected, if you remove this component.

**Comment by vasicvuk** [comment]
@prashant-shahi Yes, but As I understand I don't use any of this. I already disabled k8s infra part, and I only use metrics/traces/logs/exceptions directly pushed to otel collector for my use case.

**Comment by prashant-shahi** [comment]
@vasicvuk I see what you mean here.

I will be sure to bring it up in team discussion to introduce options to disable OtelCollector Metrics and Alertmanager for minimised set up.

**Comment by vasicvuk** [comment]
@prashant-shahi Thank you
