### ISSUE TITLE
Nginx-ingress error when installing or upgrading helm chart according to documentation

### ISSUE THREAD

**Issue by nicot4e** [SigNoz/charts#180]
When enabling the Nginx Ingress controller according to https://signoz.io/docs/tutorial/setting-up-tls-for-signoz/#enable-nginx-ingress-controller I get the following message:

`post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook signoz/templates/cert-issuer.yaml: error validating "": error validating data: ValidationError(ClusterIssuer.spec.acme.solvers[0]): unknown field "ingress" in io.cert-manager.v1.ClusterIssuer.spec.acme.solvers`

Is this a compatibility issue? Is there any workaround? I've tried multiple combinations of override-values.yaml configuration to no avail.

Some details about my setup:
A fresh and pretty standard Google GKE Kubernetes cluster version 1.24.9-gke.2000 (I switched back to a standard cluster because Helm install on a GKE autopilot cluster didn't work, I guess I'm waiting for  #175 )

**Comment by prashant-shahi** [comment]
@nicot4e Support PR for Autopilot has been merged.

Please do let us know if the the reported issue has been resolved for you.

**Comment by prashant-shahi** [comment]
@nicot4e Thanks for the PR. It is merged and patch release `0.12.1` is out now.
