### ISSUE TITLE
attributes sanity across development and production environments

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/charts#191]
For development environment, people tend to install SigNoz in same cluster as that of their application.
We will need to have processors like Resource detection and K8s attribute in the pipelines in SIgNoz OtelCollector.

However, in case of production environment, people will likely have dedicated K8s cluster for SigNoz while having their applications in deployed in another cluster.
In that scenario, adding attributes/labels from signoz k8s cluster to the telemetry data generated from application k8s cluster would not be right.

Also, we need to consider the case where data is being sent via OtelCollector binary or scraping metrics exporter.

/cc @SigNoz/devops @SigNoz/backend

**Comment by grandwizard28** [comment]
Addressed by:
- https://github.com/SigNoz/charts/pull/477
- https://github.com/SigNoz/charts/pull/488
- https://github.com/SigNoz/charts/pull/504
- https://github.com/SigNoz/charts/pull/533
