### ISSUE TITLE
Target issue metrics exporter

### ISSUE THREAD

**Issue by Atomzwieback** [SigNoz/charts#22]
We deployed the chart but it seems like the target hostname here:

https://github.com/SigNoz/charts/blob/9a01e14aba7838eac7037249a0de42e17b638026/charts/signoz/values.yaml#L832

does not take into account the "release name". This means in our case `otel-collector:8889` does not resolve and the service throws errors. So we used the name including the release name and then it works like this `signoz-otel-collector:8889`

I guess its not only a problem on our side?

**Comment by prashant-shahi** [comment]
@Atomzwieback Thanks for pointing that out.
Yes, it looks like we missed it out when introducing single config template for OtelCollector Metrics.
