### ISSUE TITLE
signoz helm charts having problem

### ISSUE THREAD

**Issue by bittu664** [SigNoz/charts#229]
hello team , when i was installing this helm charts by using this command. it gives me error like this , i want a proper solutions.

```
helm --namespace platform install signoz signoz/signoz
```

![Screenshot 2023-05-19 at 8 31 39 PM](https://github.com/SigNoz/charts/assets/28609215/c64a0c19-bcdc-45f2-95fc-03fc77517f0f)

**Comment by prashant-shahi** [comment]
Hello @bittu664 :wave: 
This issue is seen in older version of Helm.

Can you upgrade the Helm version >= 3.8?

**Comment by bittu664** [comment]
hello @prashant-shahi  after upgrading the helm , now its working but after the installation why this pods crashbackloopoff.
<img width="1206" alt="Screenshot 2023-05-19 at 11 24 05 PM" src="https://github.com/SigNoz/charts/assets/28609215/4ce87ee3-4f04-47b2-abdc-1091eb3705d1">

**and here is the logs:-**

<img width="1438" alt="Screenshot 2023-05-19 at 11 23 56 PM" src="https://github.com/SigNoz/charts/assets/28609215/78226287-f7bb-4843-8d82-61ba355aa68a">

**Comment by bittu664** [comment]
now today i can see  lots of error , here is the screenshot:-

![Screenshot 2023-05-20 at 9 06 08 PM](https://github.com/SigNoz/charts/assets/28609215/d2c449ad-96ff-40b1-b9a8-e69211d6d65c)

**Comment by prashant-shahi** [comment]
@bittu664 It seems like the clickhouse server is not healthy.
It would be helpful if you could share `kubectl describe` output of clickhouse pod and associated pv/pvc.

Regarding the previous error in clickhouse logs exporter, @nityanandagohain would be right person to help out.

**Comment by nityanandagohain** [comment]
Somehow you got stuck in dirty migration.

If old logs data is not a priority then do the following

* Stop the otel-collector.
* Exec into clickhouse `k exec -it chi-my-release-clickhouse-cluster-0-0-0 -n platform -- /bin/sh`
* Run clickhouse client `clickhouse client`
* Drop the logs database `drop database signoz_logs`
* Start your otel-collector
