### ISSUE TITLE
Signoz pods are not getting up

### ISSUE THREAD

**Issue by vinay-unify-care** [SigNoz/charts#232]
Dear Team,
We have installed Signoz in EKS cluster- there are sufficient nodes with enough memory and CPU, but when we describe pods, pods are not getting up and not showing any error.
 PFB.
![image](https://github.com/SigNoz/charts/assets/117142844/5edb1f12-6228-4e82-afb1-aac25de5a4b2)

When further POD/deployment is described- no error showing.

 **kubectl describe pod uc-care-monitor-signoz-otel-collector-6f5f56d894-lr9l9 -n uc-tools**

![image](https://github.com/SigNoz/charts/assets/117142844/5a0e2e95-d63c-44ab-a7fd-14e20fb8a1be)

Please note we have installed Signoz in the custom namespace- not in the platform
![image](https://github.com/SigNoz/charts/assets/117142844/1af3ad40-1426-4814-bef8-ca6d05d7c794)

**Comment by prashant-shahi** [comment]
@vinay-unify-care Can you verify that clickhouse is healthy? It should be possible with chi logs and pod state.

The issue above is mostly seen when clickhouse pod takes times to be ready.
In the above shared information, I see that clickhouse was up 11h ago, but rest of the pods are new.

If you had previous instance of signoz release, be sure to properly uninstall before retrying.
https://signoz.io/docs/operate/kubernetes/#uninstall-signoz-cluster

**Comment by vinay-unify-care** [comment]
Thanks @prashant-shahi - but actually we tried to restart signoz using, below command,
helm upgrade --recreate-pods uc-care signoz/signoz -f override-values.yaml --namespace uc-tools( pls not clickhouse service is not getting restarted)
but when further verified found that the node where click house is shown running is not present in the cluster. can you suggest steps to remove cluster-
![image](https://github.com/SigNoz/charts/assets/117142844/ce1bc173-1b73-4321-b132-385cfec776e5)

**Comment by prashant-shahi** [comment]
@vinay-unify-care I see that supposed node where clickhouse is supposed to run is no longer available in the cluster.
You could try uninstalling properly first before installing again: https://signoz.io/docs/operate/kubernetes/#uninstall-signoz-cluster

Moreover, one of the prerequisites for helm chart is that you use "Managed nodes - Linux, since Fargate is not officially supported". Would it be possible for you to use an independent k8s cluster with managed nodes instead?

https://signoz.io/docs/install/kubernetes/aws/#prerequisites

**Comment by vinay-unify-care** [comment]
Thanks, @prashant-shahi. If I would like to persist data(previous logs/users info) for the new installation how to do it?
We are using EKS with managed nodes only. Please suggest ?

**Comment by vinay-unify-care** [comment]
Hi @prashant-shahi , am trying to uninstall Signoz and do a clean setup again, but when trying to uninstall- click house pods are not getting terminated due to PVC  attached. Can you please help how to delete the associated pvc.?
![image](https://github.com/SigNoz/charts/assets/117142844/fb8ab432-91ba-4aa5-92db-82a40133ff1e)

**Comment by prashant-shahi** [comment]
This mostly happens when you try to delete the volumes prior to properly deleting the ClickHouse Instance.

You can resolve this by patching the PVCs in the namespace:

```bash
kubectl get -n platform pvc -o=name | xargs kubectl patch \
  -n platform \
  -p '{"metadata":{"finalizers":[]}}' --type=merge
```

Ref: https://signoz-community.slack.com/archives/C01HWUTP4HH/p1685101696597769?thread_ts=1685085415.450749&cid=C01HWUTP4HH

**Comment by vinay-unify-care** [comment]
It worked. @prashant-shahi  Thank you.. ..!!
