### ISSUE TITLE
Error when pulling image

### ISSUE THREAD

**Issue by 3pmsundayafternoon** [SigNoz/charts#237]
Installing using `helm install -n platform  --create-namespace my-release signoz/signoz`.

Pods fail to pull images. Does anyone have any idea what is happening?

![image_pull_backoff](https://github.com/SigNoz/charts/assets/58926684/856dcb1a-56bb-45e8-91fc-bdccd97bdf87)

I'm developing locally using https://kind.sigs.k8s.io/ as my cluster.

**Comment by freshstartagain** [comment]
Fixed this issue by restarting my machine.
