### ISSUE TITLE
Use `global.image.registry` as default registry for subcharts

### ISSUE THREAD

**Issue by shivanshu1333** [SigNoz/charts#272]
use `global.image.registry` as a default registry when set for all the sub charts, currently it is missing for `otelCollector.image` and maybe be missing for others as well.
Detailed discussion here https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1692020711150209

**Comment by prashant-shahi** [comment]
We already have support for global registry as you can see [here](https://github.com/SigNoz/charts/blob/main/charts/signoz/templates/_helpers.tpl#L360-L369).

You need to use `global.imageRegistry` configuration instead.

**Comment by srikanthccv** [comment]
This is not done. Please read the linked conversation again. There are some places where globalRegistry doesn't take effect.

**Comment by srikanthccv** [comment]
You are correct.
