### ISSUE TITLE
Missing reclaim policy for PVC

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/charts#323]
The default reclaim policy for PVC from the operator is `Delete` https://github.com/Altinity/clickhouse-operator/blob/689d35c207b4b189adfa7d3171b9a606b6cfa44e/pkg/model/volumer.go#L39-L53. We don't have any reclaim policy set here https://github.com/SigNoz/charts/blob/150ff920803984a13e314adf374bea15dc724de6/charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml#L257-L274?

They say _Use reclaimPolicy: Retain in all your cluster resource definitions._ here https://altinity.com/blog/preventing-clickhouse-storage-deletion-with-the-altinity-kubernetes-operator-reclaimpolicy. Why do use the default `Delete` policy instead of `Retain` for PVCs also?

**Comment by prashant-shahi** [comment]
The retain policy of the PV falls back the retain policy of the used storage class.

Nevertheless, I think it's good to include the changes.

@srikanthccv do review the linked PR and let me know.

**Comment by srikanthccv** [comment]
I am confused by your usage of PV and PVC here/Slack/Notion etc and points have been incoherent. We are trying to address the PVC policy. This doesn't affect the PV policies in any way.

**Comment by prashant-shahi** [comment]
> We are trying to address the PVC policy. This doesn't affect the PV policies in any way.

yes, you are right. And the linked PR helps in that.
But I was talking wrt our previous environment, this didn't have much change in behaviour.

Let me share details about the same with you on DM.

**Comment by prashant-shahi** [comment]
PR with the changes are merged and part of `clickhouse-23.12.3` release.

Will include this from next signoz chart release
