### ISSUE TITLE
Logs explorer - timestamp

### ISSUE THREAD

**Issue by sati-max** [SigNoz/charts#337]
Hello

I'm collecting logs in signoz k8s. Everything works, logs are collected, parsed, etc without issues. I have a question - is it possible to change how SigNoz displays the timestamp on each log entry in the logs explorer view?

Currently I have something like this:
(from Logs Explorer > Default view):
![image](https://github.com/SigNoz/charts/assets/47517196/69c049ae-2c3c-4000-adb0-a890d59d86d5)

or text (not sure if the image uploaded):
log:
timestamp: 2023-11-20T14:38:18+01:00

Is there a way to delete the "**+01:00**" from the logs explorer view? (I assume it's the timezone)

Thanks

**Comment by pranay01** [comment]
@sati-max Yeah, should be possible by using Logs Pipeline. You can use processors on top of logs to change data formats.

https://signoz.io/docs/logs-pipelines/introduction/

You would need to use a recent version of SigNoz for this

**Comment by sati-max** [comment]
@pranay01  thank you. Will look into it.
