### ISSUE TITLE
Add the ability to define extra environment variables

### ISSUE THREAD

**Issue by artem-derevyanko** [SigNoz/charts#374]
When using Signoz Chart, I am having problems with K8S infrastructure monitoring. I am getting errors in `k8s-infra-otel-agent`:

```
2024-01-09T13:21:43.211Z	error	scraperhelper/scrapercontroller.go:200	Error scraping metrics	{"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://scw-node-default-19b03403107a40efb3ca15f15287b:10250/stats/summary\": dial tcp: lookup scw-node-default-19b03403107a40efb3ca15f15287b on 10.32.0.10:53: no such host", "scraper": "kubeletstats"}
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
	go.opentelemetry.io/collector/receiver@v0.88.0/scraperhelper/scrapercontroller.go:200
```

Inside the cluster I cannot use a node name as endpoint, but I can use a node IP. The problem seems to be the same as [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26481). 

Here is the code that specifies the default endpoint value:

https://github.com/SigNoz/charts/blob/1f452e6469ea7bf23838708c46969ffd2b6311b7/charts/k8s-infra/values.yaml#L212-L217

Is there any possibility to add the ability to define extra envs in `values.yaml`?

Something like that:

```yaml
extraEnvs:
  - name: NODE_IP
     valueFrom:
       fieldRef:
         apiVersion: v1
         fieldPath: status.hostIP

k8s-infra:
  presets:
    kubeletMetrics:
      endpoint: 'https://${env:NODE_IP}:10250'
```

**Comment by prashant-shahi** [comment]
Currently, the chart supports additional envs but it only takes key-value pairs.

However, the `K8S_HOST_IP` should already be there which can be used instead.

```yaml
k8s-infra:
  presets:
    kubeletMetrics:
      endpoint: 'https://${K8S_HOST_IP}:10250'
```

https://github.com/SigNoz/charts/blob/main/charts/k8s-infra/templates/_helpers.tpl#L385-L388

**Comment by artem-derevyanko** [comment]
@prashant-shahi Thanks.

If I install `k8s-infra` chart directly, `K8S_HOST_IP` will work. If I install `signoz` chart (which uses `k8s-infra` as a dependency), `K8S_HOST_IP` will be empty.

As I understand it, if I use signoz chart, this code is used:

https://github.com/SigNoz/charts/blob/main/charts/signoz/templates/_helpers.tpl#L652-L674

but here it is not `K8S_HOST_IP`

I think adding this variable here will solve the problem. I don't know how Helm templates work exactly, but it is pretty non-obvious behavior.

**Comment by prashant-shahi** [comment]
Oh, right! That looks inconsistent across two charts.

Nice catch! Feel free to create a PR with that additional variable if possible.
