### ISSUE TITLE
Error on "helm install signoz/k8s-infra" for version 0.10.4 and 0.11.0

### ISSUE THREAD

**Issue by akalitenya** [SigNoz/charts#377]
helm install -f values/st-signoz-infra.yaml signoz-infra signoz/k8s-infra -n signoz-infra --version 0.11.0

values/st-signoz-infra.yaml
```
otelCollectorEndpoint: ingest.us.signoz.cloud:443
otelInsecure: false
signozApiKey: <API_KEY>
global:
  clusterName: some-cluster-name
```

Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:                                                                                                                                 * '' has invalid keys: otlp                                                                                                                                      
2024/01/11 13:05:13 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:  
* '' has invalid keys: otlp                                                                                                                                      
 Stream closed EOF for ...
 (signoz-infra-k8s-infra-otel-deployment) 
 
 No error for --version 0.10.3

**Comment by srikanthccv** [comment]
Please use https://github.com/SigNoz/charts/releases/tag/k8s-infra-0.11.1
