### ISSUE TITLE
Configure Email Alert Channel

### ISSUE THREAD

**Issue by Kamalsaiperla** [SigNoz/charts#439]
Hello,
I’m encountering an issue while configuring the Alert channel type email in Signoz. In the documentation provided here https://signoz.io/docs/alerts-management/notification-channel/email/#configuring-alertmanager , it mentions that I need to configure a few environment variables. However, in the UI, when configuring it, it only asks for the recipient mail address. Where do I need to configure those values to use the Email Type alert channel?
I deployed Self-Hosted Signoz using the Helm chart in Kubernetes.
<img width="1512" alt="Screenshot 2024-05-18 at 11 02 52 AM" src="https://github.com/SigNoz/charts/assets/48655495/70269d3c-8af3-4493-8cf3-e5cd8746e188">

**Comment by srikanthccv** [comment]
The doc is updated.
