### ISSUE TITLE
SMTP configuration

### ISSUE THREAD

**Issue by pascal89** [SigNoz/charts#443]
Hi,
Currently, the Signoz Helm chart doesn't support providing the [SMTP configuration](https://signoz.io/docs/operate/configuration/#query-service) explicitly. By looking into the Helm chart I already found out, I'll be able to configure this via the `queryService.additionalEnvs` chart variable, but that way I'll unfortunately have to provide my SMTP password in an unsecure way.

My suggestion is to update the Helm chart to be able to provide the SMTP configuration through Helm variables, where for the SMTP password we'll be able to provide this through an existing secret.

As I have experience with maintaining Helm charts, and I'm also willing to make a contribution for this. Please let me hear your thought on this.

**Comment by pascal89** [comment]
Hi @prashant-shahi, do you have any comments on this? Thanks in advance :-)

**Comment by grandwizard28** [comment]
Hi @pascal89,
That sound nice! Would you be willing to open a PR?

**Comment by prashant-shahi** [comment]
@pascal89 That would be great. Looking forward for your contribution.

**Comment by prashant-shahi** [comment]
This has been addressed in this PR: https://github.com/SigNoz/charts/pull/577
