### ISSUE TITLE
Custom clickhouse storageClass does not work

### ISSUE THREAD

**Issue by MattiDeGrauwe** [SigNoz/charts#482]
I'm trying to deploy our clickhouse cluster with a different storageClass using the following helm config:

```
clickhouse:
  persistence:
    size: 500Gi
    storageClass: azure-premium-v2
```

This does not seem to work, and the same default storageClass is use with **ReclaimPolicy: Delete** 

```
pvc-57a1f253-4a28-4b96-a831-0455fab5306c   500Gi      RWO            Delete           Bound    signoz/data-volumeclaim-template-chi-signoz-clickhouse-cluster-0-0-0   default                 44h
```

The code on [this](https://github.com/SigNoz/charts/blob/main/charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml#L267-L282) helm config should support adding a custome storageClass with  **ReclaimPolicy: Retain**

We are hosting SigNoz on self-hosted Azure AKS cluster
Thanks!

**Comment by grandwizard28** [comment]
Hi @MattiDeGrauwe,
Thanks for pointing that out. Would you be willing to raise a fix for this?

**Comment by grandwizard28** [comment]
Hi @MattiDeGrauwe,
When creating the `azure-premium-v2` storageclass, try specifying `ReclaimPolicy: Retain`. More information at https://kubernetes.io/docs/concepts/storage/storage-classes/
