### ISSUE TITLE
charts/k8s-infra - k8s.cluster.name missing in Otel Collector Config

### ISSUE THREAD

**Issue by yashgorana** [SigNoz/charts#506]
The PR #488 accidentally removed k8s.cluster.name from `charts/k8s-infra/values.yaml`

### Repro
Install k8s-infra otel collector with `clusterName` or `global.clusterName` set to some value
```
helm install k8s-infra k8s-infra \
        --repo https://charts.signoz.io \
        --set global.deploymentEnvironment=local \
        --set global.clusterName=test-cluster \
        --set otelCollectorEndpoint=$COLLECTOR_URL \
        --set otelInsecure=true \
        --set presets.otlpExporter.enabled=true
```
Once installed, check logs in SigNoz UI & observe that the `k8s.cluster.name` attribute missing in log details & filter pane says "No Value Found" for cluster names

<img width="884" alt="Screenshot 2024-09-25 at 3 20 40 AM" src="https://github.com/user-attachments/assets/a72039d2-779d-4386-be32-6b2923738a3f">

### Workaround

Reverting the version with `helm install ... --version 0.11.11` seems to work.
<img width="780" alt="Screenshot 2024-09-25 at 3 26 03 AM" src="https://github.com/user-attachments/assets/5016770c-6935-4f2c-a4bb-ad11bd8ee299">

**Comment by yashgorana** [comment]
Will be fixed with https://github.com/SigNoz/charts/pull/504

**Comment by grandwizard28** [comment]
This is now released! Do check if this resolves your issue!
