### ISSUE TITLE
Incorrect host.name for node system/host metrics

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/charts#513]
> Currently when a pod is created, its hostname is the Pod's metadata.name value.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

The hostname should not be the collector agent pod name.

**Comment by grandwizard28** [comment]
This should have been solved @srikanthccv with the latest release that we did.

**Comment by grandwizard28** [comment]
The problem is with the resourcedetection being system and then sources as os.
We should replace this with the appropriate cloud platform the collector is running on for our usecase.

**Comment by srikanthccv** [comment]
This is fixed now
