### ISSUE TITLE
Frontend: set proxy http version to 1.1 to avoid 426 error with Istio

### ISSUE THREAD

**Issue by nickb937** [SigNoz/charts#53]
When Istio is enabled on the namespace, I cannot successfully use the frontend with the default chart configuration because the default HTTP version used for nginx proxy is 1.0.

Istio will fail the proxy call to any /api route from the frontend with a `426 Upgrade Required`:

From the nginx on the frontend:

```
127.0.0.6 - - [11/Jul/2022:08:54:13 +0000] "GET /api/v1/version HTTP/1.1" 426 0 "https://signoz.medosync.intern/login" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "172.16.0.4"
```

From the istio-proxy on the query-service:

```
[2022-07-11T08:47:29.750Z] "GET /api/v1/version HTTP/1.0" 426 - low_version - "-" 0 0 0 - "172.16.0.4" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "5ef74ed5-2082-4f89-b23b-5d109c90df59" "mon-signoz-query-service:8080" "-" - - 10.240.0.16:8080 10.240.1.221:37958 - -
```

The solution is to set proxy version in the server config:

```
  proxy_http_version 1.1;
```

**Comment by prashant-shahi** [comment]
@nickb937 We can include the following `proxy_http_version 1.1` for following sections:
https://github.com/SigNoz/charts/blob/main/charts/signoz/templates/frontend/config.yaml#L31-L44

Do let me know if it would be possible for you to raise a PR with working changes.
If yes, I will assign it to you. :)

**Comment by prashant-shahi** [comment]
@nickb937 You should be able to follow the upgrade guide below to point to latest chart release with fixes:

https://signoz.io/docs/operate/kubernetes/#upgrade
