### ISSUE TITLE
argo is trying to install in kube-system

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [SigNoz/charts#55]
hi team,

while installing signoz in argocd chart version `0.1.4` it's trying to install Kube-system our current chart is `0.0.19` which is working fine 

Argo version `4.5.6`

Thanks and regards,
Chiranjeevi M.

**Comment by prashant-shahi** [comment]
@medicharlachiranjeevi can you share more details on how to reproduce?

> trying to install kube-system
what do you mean by that? Logs or screenshot would help.

**Comment by prashant-shahi** [comment]
Tested in latest SigNoz charts.

Not able to reproduce the issue.
