### ISSUE TITLE
Version 0.2.1:  QueryService not starts because of authentication issue

### ISSUE THREAD

**Issue by janmaslik** [SigNoz/charts#63]
Install using helm into fresh namespace:
Clickhouse starts. QueryService  stuck because of Authentication error . Rest of the pods waits for the QueryService .

QueryService error:
clickhouseReader/reader.go:108 error connecting to primary db: code: 516, message: admin: Authentication failed: password is incorrect or there is no user with such name.

Maybe i need to do something but i didnt see anything else in the installation manual

**Comment by janmaslik** [comment]
same problem for version 0.1.4 . 
Working version i know is 0.0.20

**Comment by pranay01** [comment]
@janmaslik which version of SigNoz are you trying to set up?

**Comment by prashant-shahi** [comment]
@janmaslik can you share the command you used to bring up signoz cluster?
If you used `overwrite-values.yaml` please share that as well.

**Comment by prashant-shahi** [comment]
@janmaslik can you please upgrade to the latest version?
Do let us know if it is reproducible in the newest chart v0.2.4.

Follow the instructions here:
https://signoz.io/docs/operate/kubernetes/#upgrade

**Comment by janmaslik** [comment]
Thank you for answer , guys.  
Yes, is still reproducible in v0.2.4.

Im using helm installation. My kubernetes cluster is in scaleway provider.
All i do is run command inside fresh namespace `helm -n managed-pilot-signoz install my-release signoz/signoz` as is decribed in installation manual

![image](https://user-images.githubusercontent.com/30992729/183501450-d9eac6ba-8629-4198-990a-f6451e465ec0.png)

QueryService error:
![image](https://user-images.githubusercontent.com/30992729/183501905-64976f58-98b5-4f33-bc62-e4bf2ffba74d.png)

**Comment by janmaslik** [comment]
im not putting there any other configuration at this state

**Comment by janmaslik** [comment]
Also i didnt upgraded into 0.2.4 . I uninstalled signoz and deleted whole namespace. Then created namespace and install signoz after repo upgrade

**Comment by prashant-shahi** [comment]
@janmaslik can your cluster information like k8s version, node size and types?

Also, make sure to follow the steps below to properly cleanup the SigNoz cluster:

```bash
helm -n platform uninstall my-release
kubectl -n platform delete clickhouseinstallation.clickhouse.altinity.com/signoz

# in another terminal
kubectl -n platform patch clickhouseinstallations.clickhouse.altinity.com/signoz -p '{"metadata":{"finalizers":[]}}' --type=merge

# remove all PVCs
kubectl -n platform delete pvc --all

kubectl delete namespace platform
```

**Comment by janmaslik** [comment]
hello , ran all commands . All ok, except  :
![image](https://user-images.githubusercontent.com/30992729/183522284-9dc213d3-e779-43e9-9306-d7760e88f94b.png)
Most likely because i deleted it by previous command from the list.
`kubectl -n platform delete clickhouseinstallation.clickhouse.altinity.com/signoz`


Also i tried to use same namespace as in your examples. Still same effect. QueryService has problem with authentication. Is possible that newer versions of the clickhouse  have different default credentials. Because i see in "Environment Variables" of the POD same credetials for clickhouse. And they are same as for chart version 0.0.20 ( Its signoz 0.8.2 but i dont remember clickhouse version) . And as i said, its only working version for me. 

Also checked logs for clickhouse-operator
![image](https://user-images.githubusercontent.com/30992729/183523864-8761314e-a97b-4b9a-bf07-dd73a1719a1c.png)

clickhouse logs:
![image](https://user-images.githubusercontent.com/30992729/183524301-3a221ed7-0474-4a11-80d8-a8420f3f5998.png)

**Comment by janmaslik** [comment]
Kubernetes version
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

![image](https://user-images.githubusercontent.com/30992729/183524685-2ee758bb-ed92-4ac0-a2e0-64592bbeb842.png)

**Comment by prashant-shahi** [comment]
@janmaslik Only possible reason, I could think of is the IP whitelisting.

Can you share output of the command below?
```bash
kubectl -n platform get pods -o=wide
```

Also, try the following `overwrite-values.yaml` along with helm install/update command.
```yaml
clickhouse:
  allowedNetworkIps:
    - "127.0.0.1"
    - "::/0"
```

**Comment by janmaslik** [comment]
Sure , there is the output:
![image](https://user-images.githubusercontent.com/30992729/183597325-14ccfd76-d842-4b7d-befc-eb94228d86e2.png)

Also Im going to check manual how to put custom yaml file. Then i let you know.
Thanks for help

**Comment by prashant-shahi** [comment]
Yeah, I was right. That's that issue.

You could include include `100.64.0.0/10` in the `allowedNetworkIps` along with other private IP ranges:
The following `overwrite-values.yaml` should do the trick:
```yaml
clickhouse:
  allowedNetworkIps:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "100.64.0.0/10"
```

However, that additional IP range is reserved for Carrier-grade NAT address.
So, it's likely caused by configuration in the VPC subnet.

Could you tell us about how you created the K8s cluster?

**Comment by janmaslik** [comment]
Thank you verry much.. That configuration works. About your question how did i setup cluster:
I send link to this conversation to another member of our team. He created the cluster

**Comment by prashant-shahi** [comment]
@janmaslik Feel free to DM me over community slack: https://signoz.io/slack
