### ISSUE TITLE
Otel collector endpoints not discovered after v0.10.1 upgrade

### ISSUE THREAD

**Issue by calcium90** [SigNoz/charts#66]
We've been using the helm chart deployment method and upgraded from 0.10.0 to 0.10.1. Following this it seems the endpoints for signoz-otel-collector disappeared:

`kubectl -n signoz describe svc signoz-otel-collector`
```
...
Port:              otlp  4317/TCP
TargetPort:        otlp/TCP
Endpoints:         <none>
...
```
However the signoz-otel-collector pod is up and I can connect directly to the pod IP on 4317. To resolve I've edited the deployment spec to add tcp port 4317 named as otlp and it has now been discovered. The only custom values for the chart we've used are to expand the pvc for clickhouse:
```
clickhouse:
  persistence:
    size: 40Gi
```

## Version information 
Signoz 0.10.1
Centos 7 (kernel 3.10.0-1160.36.2.el7.x86_64)
Kubernetes 1.20.9

**Comment by prashant-shahi** [comment]
@calcium90 Thank you for raising this issue. It has been resolved.

Follow the upgrade guide here:
https://signoz.io/docs/operate/kubernetes/#upgrade

**Comment by calcium90** [comment]
Thanks for the prompt resolution @prashant-shahi
