### ISSUE TITLE
Bundle external components which can be optionally enabled

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/charts#69]
For `clickhouse` chart:
- [x] Minio - S3 compatible object storage

For `signoz` chart:
- [x] Cert-Manager - Provisions and manages TLS certificates in K8s
- [x] Ingress-NGINX Controller for K8s

**Comment by RouR** [comment]
I want to use my own clickhouse instance. I don`t want to run it inside k8s. 
Need options to specify connection to clickhouse (host, port, user, password, db).
Docs is also required.

**Comment by prashant-shahi** [comment]
@RouR We already support external clickhouse server using Helm chart.
However, we are yet to create docs for it.

While we are on it, you can make changes to `externalClickhouse` configuration by referring to the `values.yaml`.
https://github.com/SigNoz/charts/blob/main/charts/signoz/values.yaml
